#!/bin/bash

COMMAND="clojure"
if ! command -v $COMMAND &> /dev/null
then
    echo "Clojure does not exist, installing"
    TMPDIR=clojure-install-tmp
    mkdir $TMPDIR
    cd $TMPDIR

    # Install Clojure
    curl -O https://download.clojure.org/install/linux-install-1.10.3.1075.sh
    chmod +x linux-install-1.10.3.1075.sh
    sudo ./linux-install-1.10.3.1075.sh

    cd ..
    rm -rf $TMPDIR
    echo "Done installing clojure"
    exit
fi
